version: "2"
services:

  django:
    restart: always
    image: gisquick/django-dev
    volumes:
      - ./_data/media:/var/www/gisquick/media/
      - ./_data/data:/var/www/gisquick/data/
      - ./_data/publish:/publish
      - ../server/webgis:/var/www/gisquick/webgis/
    environment:
      - GUNICORN_ERRORLOG=-
      - GUNICORN_ACCESSLOG=-
      - DJANGO_GISQUICK_UPLOAD_MAX_SIZE='100M'
      - DJANGO_GISQUICK_MAPSERVER_URL='http://192.168.0.16:90/cgi-bin/qgis_mapserv.fcgi'
    ports:
      - "8000:8000"